Check the condition where there is no oldLabel
If there was no label, but some are added later, the following error occurs:

```
TypeError: Cannot read property 'length' of undefined
```